### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by YoshinobuObata** [yos1up/scratch2cpp#11]
@yos1up  
[ユカイ工学株式会社](https://github.com/YUKAI)の小畑と申します．Issueからの質問で失礼しますが，弊社のサービスでこちらのリポジトリのコード (https://github.com/yos1up/scratch2cpp/blob/main/web/crx/sb3_to_cpp.js) を改変したものを使用したいのですが，ライセンスの表示がなく，ご連絡させて頂きました．使用許諾の可否と必要になる表記等を教えていただけないでしょうか．

**Comment by yos1up** [comment]
@YoshinobuObata ご連絡ありがとうございます。ライセンス表示を追加しました（MITライセンスです）。お役に立てますと幸いです。

**Comment by YoshinobuObata** [comment]
@yos1up お返事ありがとうございます！MITライセンス感謝致します．非常に参考なります！
https://kurikit.ux-xu.com/play/licenses.txt にライセンスを記載させて頂きました．
